name: firstworkflow

on:
  push:
    branches:
      - "main"

jobs:
  firstworkflowjob:
    name: firstjob
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: run maven
        run: mvn clean package
        shell: bash
